import { Badge, Checkbox } from "antd";

export const dataSource = [
  {
    key: "1",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "KLMNDTGGFY-chair",
    quantity: "126",
    status: <Badge status="success" />,
  },
  {
    key: "2",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "SDEJFGGFY-chair",
    quantity: "126",
    status: <Badge status="processing" />,
  },
  {
    key: "3",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "DHGEYDTGGFY-chair",
    quantity: "126",
    status: <Badge status="default" />,
  },
  {
    key: "4",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "KLMNDTGGFY-chair",
    quantity: "126",
    status: <Badge status="success" />,
  },
  {
    key: "5",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "SDEJFGGFY-chair",
    quantity: "126",
    status: <Badge status="processing" />,
  },
  {
    key: "6",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "DHGEYDTGGFY-chair",
    quantity: "126",
    status: <Badge status="default" />,
  },
  {
    key: "7",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "KLMNDTGGFY-chair",
    quantity: "126",
    status: <Badge status="success" />,
  },
  {
    key: "8",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "SDEJFGGFY-chair",
    quantity: "126",
    status: <Badge status="processing" />,
  },
  {
    key: "9",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "DHGEYDTGGFY-chair",
    quantity: "126",
    status: <Badge status="default" />,
  },
  {
    key: "10",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "KLMNDTGGFY-chair",
    quantity: "126",
    status: <Badge status="success" />,
  },
  {
    key: "11",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "SDEJFGGFY-chair",
    quantity: "126",
    status: <Badge status="processing" />,
  },
  {
    key: "12",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "DHGEYDTGGFY-chair",
    quantity: "126",
    status: <Badge status="default" />,
  },
  {
    key: "13",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "KLMNDTGGFY-chair",
    quantity: "126",
    status: <Badge status="success" />,
  },
  {
    key: "14",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "SDEJFGGFY-chair",
    quantity: "126",
    status: <Badge status="processing" />,
  },
  {
    key: "15",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "DHGEYDTGGFY-chair",
    quantity: "126",
    status: <Badge status="default" />,
  },
  {
    key: "16",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "KLMNDTGGFY-chair",
    quantity: "126",
    status: <Badge status="success" />,
  },
  {
    key: "17",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "SDEJFGGFY-chair",
    quantity: "126",
    status: <Badge status="processing" />,
  },
  {
    key: "18",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "DHGEYDTGGFY-chair",
    quantity: "126",
    status: <Badge status="default" />,
  },
  {
    key: "19",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "KLMNDTGGFY-chair",
    quantity: "126",
    status: <Badge status="success" />,
  },
  {
    key: "1",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "SDEJFGGFY-chair",
    quantity: "126",
    status: <Badge status="processing" />,
  },
  {
    key: "20",
    checkbox: <Checkbox />,
    productName: "Office Chair",
    price: "$600.56",
    sku: "DHGEYDTGGFY-chair",
    quantity: "126",
    status: <Badge status="default" />,
  },
];
export const columns = [
  {
    title: "Select",
    dataIndex: "checkbox",
  },
  {
    title: "Product Name",
    dataIndex: "productName",
  },
  {
    title: "Price",
    dataIndex: "price",
  },
  {
    title: "SKU",
    dataIndex: "sku",
  },

  {
    title: "Quantity",
    dataIndex: "quantity",
  },
  {
    title: "Status",
    dataIndex: "status",
  },
];
